from experta import Fact, Field

class StudentData(Fact):
    """
    Core Fact representing all known academic data about the student 
    in the current evaluation context.
    """
    cgpa = Field(float, default=0.0)
    failed_subjects = Field(int, default=0)
    attendance_pct = Field(float, default=100.0)
    year = Field(int, default=1)
    credit_completion = Field(float, default=100.0)
    income_band = Field(str, default="HIGH") 
    program = Field(str, default="General")
    subjects = Field(list, default=[])

class Recommendation(Fact):
    """ Fact generated by rules when a conclusion is reached. """
    rule_id = Field(str, mandatory=True)
    risk_level = Field(str, default="LOW")
    category = Field(str, default="risk") 
    message = Field(str, mandatory=True)
    action_tags = Field(list, default=[])
